import { useLiveQuery } from 'dexie-react-hooks'
import { ArrowLeft, Award, CalendarDays, Sparkles, TrendingUp } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { db, getSettings } from '../db/database'
import { getExerciseSessions } from '../services/workouts'
import { analyseExerciseProgression } from '../logic/progression'
import { calculateExerciseVolume, estimateOneRepMax } from '../logic/calculations'
import { actionLabels, formatNumber } from '../utils'
import { Card, EmptyState, Loading, PageHeader, Stat } from '../components/ui'

export function ExerciseDetailPage() {
  const { id = '' } = useParams(); const data = useLiveQuery(async () => { const exercise = await db.exercises.get(id); if (!exercise) return null; const sessions = await getExerciseSessions(id); const settings = await getSettings(); const records = await db.personalRecords.where('exerciseId').equals(id).toArray(); return { exercise, sessions, settings, records, analysis: analyseExerciseProgression(exercise, sessions, settings) } }, [id])
  if (data === undefined) return <Loading />; if (!data) return <div className="page"><p>Ejercicio no encontrado.</p></div>
  const { exercise, sessions, records, analysis } = data; const chart = [...sessions].reverse().map(({ workout, sets }) => { const effective = sets.filter((s) => s.completed && s.type !== 'Calentamiento'); return { date: workout.date.slice(5), peso: Math.max(0, ...effective.map((s) => s.weight || 0)), volumen: calculateExerciseVolume(effective), '1RM': Math.max(0, ...effective.map((s) => estimateOneRepMax(s.weight || 0, s.reps || 0, data.settings.oneRmFormula))) } }); const allSets = sessions.flatMap((s) => s.sets).filter((s) => s.completed)
  return <div className="page"><Link to="/ejercicios" className="back-link"><ArrowLeft /> Volver a ejercicios</Link><PageHeader eyebrow={exercise.primaryMuscle.toUpperCase()} title={exercise.name} subtitle={`${exercise.equipment} · ${exercise.progressionMethod}`} />
    <div className="stats-grid"><Stat label="Mejor peso" value={allSets.length ? `${formatNumber(Math.max(...allSets.map((s) => s.weight || 0)))} kg` : '—'} /><Stat label="Mejor 1RM estimado" value={allSets.length ? `${formatNumber(Math.max(...allSets.map((s) => estimateOneRepMax(s.weight || 0, s.reps || 0, data.settings.oneRmFormula))))} kg` : '—'} /><Stat label="Volumen acumulado" value={`${formatNumber(calculateExerciseVolume(allSets), 0)} kg`} /><Stat label="Sesiones" value={sessions.length} /></div>
    <Card className="detail-coach"><Sparkles /><div><small>RECOMENDACIÓN ACTUAL · CONFIANZA {analysis.recommendation.confidence.toUpperCase()}</small><h2>{actionLabels[analysis.recommendation.action]}{analysis.recommendation.recommendedWeight ? ` · ${formatNumber(analysis.recommendation.recommendedWeight)} kg` : ''}</h2><p>{analysis.recommendation.reason}</p><span>{exercise.usualSets} series · {exercise.targetMinReps}–{exercise.targetMaxReps} repeticiones</span>{analysis.plateau && <b className="plateau">Posible estancamiento: tres sesiones comparables sin mejora clara. No se aplicará ningún cambio automático.</b>}</div></Card>
    {chart.length ? <div className="charts-grid"><Card><div className="section-title"><div><TrendingUp /><span><small>EVOLUCIÓN</small><h2>Peso y 1RM estimado</h2></span></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid strokeDasharray="3 3" stroke="var(--line)" /><XAxis dataKey="date" stroke="var(--muted)" /><YAxis stroke="var(--muted)" /><Tooltip contentStyle={{ background: 'var(--panel)', border: '1px solid var(--line)', borderRadius: 12 }} /><Line type="monotone" dataKey="peso" stroke="#c9ff3f" strokeWidth={3} dot={{ r: 3 }} /><Line type="monotone" dataKey="1RM" stroke="#69b7ff" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div></Card><Card><div className="section-title"><div><Award /><span><small>HISTORIAL</small><h2>Marcas personales</h2></span></div></div>{records.length ? records.map((r) => <div className="record-row" key={r.id}><Award /><div><strong>{r.type}</strong><small>{r.achievedAt.slice(0,10)}</small></div><b>{formatNumber(r.value)}</b></div>) : <EmptyState icon={<Award />} title="Sin marcas todavía" text="Completa series válidas para detectar récords." />}</Card></div> : <EmptyState icon={<CalendarDays />} title="Aún no hay historial" text="Añade este ejercicio a una sesión y completa al menos una serie." />}
    {sessions.length > 0 && <Card><h2>Sesiones</h2><div className="session-table">{sessions.map(({ workout, sets }) => <Link to={`/historial/${workout.id}`} key={workout.id}><span>{workout.date}</span><b>{sets.filter((s) => s.completed).map((s) => `${s.weight || 0}×${s.reps || 0}`).join(' · ')}</b><small>{formatNumber(calculateExerciseVolume(sets), 0)} kg</small></Link>)}</div></Card>}
  </div>
}
