import { useMemo, useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { Activity, CalendarDays, Copy, Dumbbell, Flame, Search, Trash2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { db, deleteWorkoutCascade } from '../db/database'
import { calculateWorkoutVolume } from '../logic/calculations'
import { nowIso, uid, formatNumber } from '../utils'
import { Card, EmptyState, PageHeader, Select } from '../components/ui'

export function HistoryPage() {
  const navigate = useNavigate(); const [query, setQuery] = useState(''); const [status, setStatus] = useState('Todas'); const [view, setView] = useState<'list' | 'calendar'>('list')
  const data = useLiveQuery(async () => { const workouts = await db.workouts.orderBy('date').reverse().toArray(); const links = await db.workoutExercises.toArray(); const sets = await db.sets.toArray(); const cardio = await db.cardio.toArray(); const wods = await db.wods.toArray(); const exercises = await db.exercises.toArray(); return { workouts, links, sets, cardio, wods, exercises } }, [])
  const filtered = useMemo(() => data?.workouts.filter((w) => (status === 'Todas' || (status === 'Completadas' ? w.status === 'completed' : w.status === 'active')) && `${w.name} ${w.type} ${w.date}`.toLowerCase().includes(query.toLowerCase())) || [], [data, query, status])
  async function duplicate(id: string) { if (!data) return; const source = data.workouts.find((w) => w.id === id); if (!source) return; if (data.workouts.some((w) => w.status === 'active')) { toast.error('Ya existe una sesión activa'); return } const newId = uid(), now = nowIso(); await db.transaction('rw', [db.workouts, db.workoutExercises, db.sets], async () => { await db.workouts.add({ ...source, id: newId, date: new Date().toISOString().slice(0,10), startTime: new Date().toTimeString().slice(0,5), endTime: null, status: 'active', createdAt: now, updatedAt: now }); for (const oldLink of data.links.filter((l) => l.workoutId === id)) { const newLinkId = uid(); await db.workoutExercises.add({ ...oldLink, id: newLinkId, workoutId: newId, createdAt: now, updatedAt: now }); await db.sets.bulkAdd(data.sets.filter((s) => s.workoutExerciseId === oldLink.id).map((s) => ({ ...s, id: uid(), workoutExerciseId: newLinkId, completed: false, completedAt: null, createdAt: now, updatedAt: now }))) } }); toast.success('Sesión duplicada como borrador'); navigate('/entrenamiento') }
  return <div className="page"><PageHeader eyebrow="MEMORIA DE ENTRENAMIENTO" title="Historial" subtitle="Cada sesión, serie y contexto en un solo lugar." /><div className="filter-bar"><div className="search"><Search /><input aria-label="Buscar historial" placeholder="Buscar por nombre, tipo o fecha…" value={query} onChange={(e) => setQuery(e.target.value)} /></div><Select value={status} onChange={(e) => setStatus(e.target.value)}><option>Todas</option><option>Completadas</option><option>Incompletas</option></Select><div className="segmented"><button className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}>Lista</button><button className={view === 'calendar' ? 'active' : ''} onClick={() => setView('calendar')}>Calendario</button></div></div>
    {!filtered.length ? <EmptyState icon={<CalendarDays />} title="Tu historial está vacío" text="Las sesiones que registres aparecerán aquí. No cargamos entrenamientos de ejemplo." /> : view === 'calendar' ? <div className="calendar-view">{Array.from(new Set(filtered.map((w) => w.date.slice(0,7)))).map((month) => <Card key={month}><h3>{new Intl.DateTimeFormat('es-ES', { month: 'long', year: 'numeric' }).format(new Date(`${month}-02`))}</h3><div>{filtered.filter((w) => w.date.startsWith(month)).map((w) => <Link key={w.id} to={`/historial/${w.id}`}><b>{w.date.slice(8,10)}</b><span>{w.name || w.type}</span></Link>)}</div></Card>)}</div> : <div className="history-list">{filtered.map((workout) => { const links = data!.links.filter((l) => l.workoutId === workout.id); const sessionSets = data!.sets.filter((s) => links.some((l) => l.id === s.workoutExerciseId)); return <Card key={workout.id} className="history-card"><Link to={workout.status === 'active' ? '/entrenamiento' : `/historial/${workout.id}`} className="history-main"><div className="date-block"><strong>{workout.date.slice(8,10)}</strong><span>{new Intl.DateTimeFormat('es-ES', { month: 'short' }).format(new Date(`${workout.date}T12:00`))}</span></div><div><span className="muscle-badge">{workout.status === 'active' ? 'EN CURSO' : workout.type}</span><h3>{workout.name || workout.type}</h3><p>{links.map((l) => data!.exercises.find((e) => e.id === l.exerciseId)?.name).filter(Boolean).join(' · ') || 'Sin ejercicios de fuerza'}</p><div className="history-meta"><span><Dumbbell /> {links.length} ejercicios</span><span><Activity /> {sessionSets.length} series</span>{data!.cardio.some((x) => x.workoutId === workout.id) && <span><Activity /> Cardio</span>}{data!.wods.some((x) => x.workoutId === workout.id) && <span><Flame /> WOD</span>}<b>{formatNumber(calculateWorkoutVolume(sessionSets), 0)} kg</b></div></div></Link><div className="history-actions"><button onClick={() => duplicate(workout.id)} aria-label="Duplicar"><Copy /></button><button onClick={async () => { if (confirm('¿Eliminar esta sesión y todos sus datos?')) { await deleteWorkoutCascade(workout.id); toast.success('Sesión eliminada') } }} aria-label="Eliminar"><Trash2 /></button></div></Card> })}</div>}
  </div>
}
