import { useRef, useState, type ChangeEvent } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { AlertTriangle, CheckCircle2, Cloud, Database, Download, Library, LogIn, LogOut, RefreshCw, Settings as SettingsIcon, Upload } from 'lucide-react'
import { toast } from 'sonner'
import { basicExercises } from '../db/seeds'
import { db, defaultSettings } from '../db/database'
import { downloadFile, exportBackup, importBackup, toCsv, validateBackup } from '../services/backup'
import type { AppSettings, BackupData } from '../types'
import { nowIso } from '../utils'
import { Button, Card, Input, Modal, PageHeader, Select } from '../components/ui'
import { useCloudSync } from '../app/CloudSyncProvider'

function ImportPreview({ data, onClose }: { data: BackupData; onClose: () => void }) {
  const apply = async (mode: 'merge' | 'replace') => { if (mode === 'replace' && !confirm('Esto reemplazará todos los datos locales. ¿Continuar?')) return; await importBackup(data, mode); toast.success(mode === 'merge' ? 'Copia fusionada' : 'Datos reemplazados'); onClose() }
  return <Modal title="Vista previa de la copia" onClose={onClose}><div className="import-preview"><p>Exportada el <b>{new Date(data.exportedAt).toLocaleString('es-ES')}</b> · esquema v{data.version}</p><div><span><b>{data.exercises.length}</b> ejercicios</span><span><b>{data.workouts.length}</b> sesiones</span><span><b>{data.sets.length}</b> series</span><span><b>{data.bodyMeasurements.length}</b> mediciones</span></div><p>Al fusionar, los identificadores duplicados se actualizan una sola vez. Al reemplazar, se borra primero la base local.</p><div className="form-actions"><Button variant="secondary" onClick={() => apply('merge')}>Fusionar datos</Button><Button variant="danger" onClick={() => apply('replace')}>Reemplazar todo</Button></div></div></Modal>
}

export function SettingsPage() {
  const stored = useLiveQuery(() => db.settings.get('settings'), [])
  const cloud = useCloudSync()
  const settings = stored || defaultSettings; const [preview, setPreview] = useState<BackupData | null>(null); const fileRef = useRef<HTMLInputElement>(null)
  const update = (patch: Partial<AppSettings>) => db.settings.put({ ...settings, ...patch, id: 'settings', updatedAt: nowIso() })
  async function backup() { const data = await exportBackup(); downloadFile(`pulso-copia-${new Date().toISOString().slice(0,10)}.json`, JSON.stringify(data, null, 2), 'application/json'); toast.success('Copia de seguridad descargada') }
  async function readFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; try { setPreview(validateBackup(JSON.parse(await file.text()))) } catch { toast.error('El archivo no tiene un formato de copia compatible') } finally { event.target.value = '' } }
  async function exportCsv(kind: 'workouts' | 'body' | 'exercises') { const rows = kind === 'workouts' ? await db.workouts.toArray() : kind === 'body' ? await db.bodyMeasurements.toArray() : await db.exercises.toArray(); downloadFile(`pulso-${kind}.csv`, `\ufeff${toCsv(rows as unknown as Record<string, unknown>[])}`, 'text/csv;charset=utf-8'); toast.success('CSV descargado') }
  async function loadLibrary() { const currentNames = new Set((await db.exercises.toArray()).map((e) => e.name)); const fresh = basicExercises().filter((e) => !currentNames.has(e.name)); if (fresh.length) await db.exercises.bulkAdd(fresh); await update({ onboardingDone: true }); toast.success(`${fresh.length} ejercicios añadidos`) }
  async function login() { try { await cloud.login() } catch { toast.error('No se ha podido acceder con Google') } }
  async function sync() { await cloud.syncNow() }
  const cloudBusy = cloud.status === 'connecting' || cloud.status === 'syncing'
  const statusText = cloud.status === 'connecting' ? 'Conectando…' : cloud.status === 'syncing' ? 'Sincronizando…' : cloud.status === 'error' ? 'Error de sincronización' : 'Sincronizado'
  return <div className="page"><PageHeader eyebrow="TU CUENTA" title="Ajustes" subtitle="Tu nube, tus unidades y lo esencial para entrenar." />
    {cloud.user ? <Card className="cloud-card cloud-connected"><CheckCircle2 /><div className="cloud-copy"><small>COPIA PRIVADA ACTIVA</small><h2>Tu progreso está protegido</h2><p>{cloud.user.email} · {statusText}{cloud.lastSyncedAt ? ` · ${new Date(cloud.lastSyncedAt).toLocaleTimeString('es-ES', { hour: '2-digit', minute: '2-digit' })}` : ''}</p><label className="remember-control"><input type="checkbox" checked={cloud.rememberMe} onChange={(event) => void cloud.setRememberMe(event.target.checked)} /> Recordarme en este dispositivo</label>{cloud.error && <p className="cloud-error">{cloud.error}</p>}</div><div className="cloud-actions"><Button onClick={sync} disabled={cloudBusy}><RefreshCw className={cloudBusy ? 'spin' : ''} /> Sincronizar</Button><Button variant="ghost" onClick={() => void cloud.logout()} disabled={cloudBusy}><LogOut /> Salir</Button></div></Card> : <Card className="cloud-card"><Cloud /><div className="cloud-copy"><small>COPIA EN LA NUBE</small><h2>Lleva Pulso contigo</h2><p>Recupera tus entrenamientos en cualquier dispositivo. Lo que ya tienes se conservará.</p><label className="remember-control"><input type="checkbox" checked={cloud.rememberMe} onChange={(event) => void cloud.setRememberMe(event.target.checked)} /> Recordarme en este dispositivo</label>{cloud.error && <p className="cloud-error">{cloud.error}</p>}</div><Button onClick={login} disabled={cloudBusy}><LogIn /> {cloudBusy ? 'Conectando…' : 'Continuar con Google'}</Button></Card>}
    {!cloud.user && <Card className="local-warning"><AlertTriangle /><div><h3>Ahora mismo solo existe una copia en este navegador.</h3><p>Hasta que conectes Google, evita borrar los datos del sitio y descarga copias JSON periódicas.</p></div></Card>}
    <div className="settings-grid"><Card><div className="section-title"><div><SettingsIcon /><span><small>LO ESENCIAL</small><h2>Entrenamiento</h2></span></div></div><div className="form-grid"><Select label="Tema" value={settings.theme} onChange={(e) => update({ theme: e.target.value as AppSettings['theme'] })}><option value="dark">Oscuro</option><option value="light">Claro</option><option value="system">Automático</option></Select><Select label="Unidad de peso" value={settings.weightUnit} onChange={(e) => update({ weightUnit: e.target.value as 'kg' | 'lb' })}><option value="kg">Kilogramos</option><option value="lb">Libras</option></Select><Input label="Descanso (segundos)" type="number" min="0" step="15" value={settings.defaultRestSeconds} onChange={(e) => update({ defaultRestSeconds: Number(e.target.value) })} /><Select label="Registrar esfuerzo con" value={settings.preferredEffort} onChange={(e) => update({ preferredEffort: e.target.value as 'RIR' | 'RPE' })}><option>RIR</option><option>RPE</option></Select></div><div className="toggle-list"><label><input type="checkbox" checked={settings.autoTimer} onChange={(e) => update({ autoTimer: e.target.checked })} /> Temporizador automático</label><label><input type="checkbox" checked={settings.vibration} onChange={(e) => update({ vibration: e.target.checked })} /> Vibración al terminar</label></div></Card>
      <Card><div className="section-title"><div><Database /><span><small>TUS DATOS</small><h2>Copia manual</h2></span></div></div><p className="muted-copy">La nube trabaja sola. El archivo JSON es una segunda copia que puedes guardar donde quieras.</p><div className="button-stack"><Button onClick={backup}><Download /> Descargar copia</Button><Button variant="secondary" onClick={() => fileRef.current?.click()}><Upload /> Restaurar copia</Button><input ref={fileRef} type="file" hidden accept="application/json,.json" onChange={readFile} /></div><details className="advanced-settings"><summary>Más opciones</summary><div className="form-grid"><Select label="Unidad de distancia" value={settings.distanceUnit} onChange={(e) => update({ distanceUnit: e.target.value as 'km' | 'mi' })}><option value="km">Kilómetros</option><option value="mi">Millas</option></Select><Select label="Fórmula de 1RM" value={settings.oneRmFormula} onChange={(e) => update({ oneRmFormula: e.target.value as AppSettings['oneRmFormula'] })}><option>Epley</option><option>Brzycki</option><option>Lombardi</option></Select><Input label="Subida máxima (%)" type="number" min="1" max="10" value={settings.maxIncreasePercent} onChange={(e) => update({ maxIncreasePercent: Math.min(10, Math.max(1, Number(e.target.value))) })} /><Input label="Sesiones antes de subir" type="number" min="1" max="5" value={settings.sessionsBeforeIncrease} onChange={(e) => update({ sessionsBeforeIncrease: Number(e.target.value) })} /></div><div className="secondary-tools"><Button variant="ghost" onClick={() => exportCsv('workouts')}>CSV entrenamientos</Button><Button variant="ghost" onClick={() => exportCsv('body')}>CSV peso</Button><Button variant="ghost" onClick={() => exportCsv('exercises')}>CSV ejercicios</Button><Button variant="ghost" onClick={loadLibrary}><Library /> Añadir biblioteca básica</Button></div></details><p className="privacy-foot">Sin analítica · sin publicidad</p></Card></div>
    {preview && <ImportPreview data={preview} onClose={() => setPreview(null)} />}
  </div>
}
