import { useEffect, useState, type FormEvent } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { Activity, ArrowDown, ArrowUp, Check, Copy, Dumbbell, Flame, Plus, RotateCcw, Timer, Trash2, Trophy, X, Zap } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { db, getSettings } from '../db/database'
import { getExerciseSessions } from '../services/workouts'
import { generateCoachRecommendation } from '../logic/progression'
import { calculateExerciseVolume, calculateWorkoutVolume, effectiveSets, totalReps } from '../logic/calculations'
import { detectPersonalRecords } from '../logic/records'
import type { CardioEntry, Exercise, SetEntry, SetType, WodEntry, Workout, WorkoutExercise } from '../types'
import { actionLabels, formatNumber, localDate, localTime, nowIso, uid } from '../utils'
import { Button, Card, EmptyState, Input, Modal, PageHeader, Select } from '../components/ui'

function StartWorkout({ onStart }: { onStart: (workout: Workout) => Promise<void> }) {
  const [date, setDate] = useState(localDate()); const [time, setTime] = useState(localTime()); const [name, setName] = useState(''); const [type, setType] = useState<Workout['type']>('Gimnasio'); const [notes, setNotes] = useState('')
  async function submit(e: FormEvent) { e.preventDefault(); const now = nowIso(); await onStart({ id: uid(), date, startTime: time, endTime: null, name, type, notes, status: 'active', energy: null, effort: null, performance: null, fatigue: null, sleepQuality: null, sleepHours: null, pain: '', comments: '', createdAt: now, updatedAt: now }) }
  return <div className="page start-workout"><PageHeader eyebrow="REGISTRO MANUAL" title="¿Qué vas a entrenar?" subtitle="Pulso no crea la sesión. Tú añades cada ejercicio cuando lo necesites." /><Card><form onSubmit={submit} className="form-grid"><Input label="Fecha" type="date" required value={date} onChange={(e) => setDate(e.target.value)} /><Input label="Hora de inicio" type="time" required value={time} onChange={(e) => setTime(e.target.value)} /><Input label="Nombre opcional" placeholder="Ej. Pierna y técnica" value={name} onChange={(e) => setName(e.target.value)} /><Select label="Tipo de sesión" value={type} onChange={(e) => setType(e.target.value as Workout['type'])}>{['Gimnasio','Fuerza','Hipertrofia','CrossFit','Cardio','Mixto','Otro'].map((x) => <option key={x}>{x}</option>)}</Select><label className="field full"><span>Notas generales</span><textarea value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="Opcional" /></label><Button className="full start-button"><Zap /> Iniciar sesión</Button></form></Card></div>
}

function RestTimer({ initial }: { initial: number }) {
  const [remaining, setRemaining] = useState(initial); const [running, setRunning] = useState(false)
  useEffect(() => { if (!running) return; const id = window.setInterval(() => setRemaining((r) => { if (r <= 1) { setRunning(false); if ('vibrate' in navigator) navigator.vibrate(250); return 0 } return r - 1 }), 1000); return () => clearInterval(id) }, [running])
  const display = `${Math.floor(remaining / 60)}:${String(remaining % 60).padStart(2, '0')}`
  return <div className={`rest-timer ${remaining === 0 ? 'done' : ''}`}><Timer /><button onClick={() => setRunning(!running)}>{running ? 'Pausar' : 'Iniciar'}</button><strong>{display}</strong><button onClick={() => setRemaining(Math.max(0, remaining - 15))}>−15</button><button onClick={() => setRemaining(remaining + 15)}>+15</button><button onClick={() => { setRemaining(initial); setRunning(false) }} aria-label="Reiniciar"><RotateCcw /></button></div>
}

function SetRow({ set, increment, onComplete }: { set: SetEntry; increment: number; onComplete: (set: SetEntry) => void }) {
  const patch = (changes: Partial<SetEntry>) => db.sets.update(set.id, { ...changes, updatedAt: nowIso() })
  async function complete() { const completed = !set.completed; await patch({ completed, completedAt: completed ? nowIso() : null }); onComplete({ ...set, completed }) }
  return <div className={`set-row ${set.completed ? 'completed' : ''}`}><div className="set-number">{set.order + 1}</div><Select aria-label="Tipo de serie" value={set.type} onChange={(e) => patch({ type: e.target.value as SetType })}>{['Calentamiento','Aproximación','Efectiva','Drop set','Back-off','Al fallo','Técnica','Otro'].map((x) => <option key={x}>{x}</option>)}</Select><div className="step-input"><button onClick={() => patch({ weight: Math.max(0, (set.weight || 0) - increment) })}>−</button><input aria-label="Peso" type="number" min="0" step="any" value={set.weight ?? ''} onChange={(e) => patch({ weight: e.target.value === '' ? null : Number(e.target.value) })} /><span>kg</span><button onClick={() => patch({ weight: (set.weight || 0) + increment })}>+</button></div><div className="step-input reps"><button onClick={() => patch({ reps: Math.max(0, (set.reps || 0) - 1) })}>−</button><input aria-label="Repeticiones" type="number" min="0" value={set.reps ?? ''} onChange={(e) => patch({ reps: e.target.value === '' ? null : Number(e.target.value) })} /><span>reps</span><button onClick={() => patch({ reps: (set.reps || 0) + 1 })}>+</button></div><input className="mini-input" aria-label="RIR" type="number" min="0" max="5" placeholder="RIR" value={set.rir ?? ''} onChange={(e) => patch({ rir: e.target.value === '' ? null : Number(e.target.value) })} /><input className="mini-input" aria-label="RPE" type="number" min="1" max="10" step=".5" placeholder="RPE" value={set.rpe ?? ''} onChange={(e) => patch({ rpe: e.target.value === '' ? null : Number(e.target.value) })} /><button className="complete-set" onClick={complete} aria-label="Marcar serie completada"><Check /></button><button className="icon-btn" onClick={() => db.sets.delete(set.id)} aria-label="Eliminar serie"><Trash2 /></button></div>
}

function ExerciseBlock({ link, exercise, sets, onRecord }: { link: WorkoutExercise; exercise: Exercise; sets: SetEntry[]; onRecord: (message: string) => void }) {
  const settings = useLiveQuery(() => getSettings(), [])
  const sessions = useLiveQuery(() => getExerciseSessions(exercise.id), [exercise.id])
  const recommendation = settings && sessions ? generateCoachRecommendation(exercise, sessions.filter((s) => s.workout.id !== link.workoutId), settings) : null
  const previous = sessions?.find((s) => s.workout.id !== link.workoutId); const lastWorking = previous?.sets.filter((s) => s.completed && s.type !== 'Calentamiento') || []
  async function addSet(copy?: SetEntry) { const now = nowIso(); await db.sets.add({ id: uid(), workoutExerciseId: link.id, order: sets.length, type: copy?.type || 'Efectiva', weight: copy?.weight ?? recommendation?.recommendedWeight ?? null, reps: copy?.reps ?? exercise.targetMinReps, rir: null, rpe: null, completed: false, notes: '', completedAt: null, createdAt: now, updatedAt: now }) }
  async function completed(set: SetEntry) { if (!set.completed) return; const previousRecords = await db.personalRecords.where('exerciseId').equals(exercise.id).toArray(); const records = detectPersonalRecords(exercise.id, link.workoutId, [...sets.filter((s) => s.id !== set.id), set], previousRecords); if (records.length) { onRecord(`Nueva marca: ${records[0].type}`); toast.success(`🏆 ${records[0].type}`, { description: exercise.name }) } }
  return <Card className="workout-exercise"><div className="workout-exercise-head"><div><span className="muscle-badge">{exercise.primaryMuscle}</span><h2>{exercise.name}</h2><p>{exercise.perDumbbell ? 'Peso por mancuerna' : exercise.equipment}</p></div><div className="exercise-head-actions"><button aria-label="Subir ejercicio" onClick={() => db.workoutExercises.update(link.id, { order: Math.max(0, link.order - 1) })}><ArrowUp /></button><button aria-label="Bajar ejercicio" onClick={() => db.workoutExercises.update(link.id, { order: link.order + 1 })}><ArrowDown /></button><button aria-label="Eliminar ejercicio" onClick={async () => { if (confirm(`¿Quitar ${exercise.name} de esta sesión?`)) { await db.sets.where('workoutExerciseId').equals(link.id).delete(); await db.workoutExercises.delete(link.id) } }}><X /></button></div></div>
    <div className="memory-strip"><div><small>ÚLTIMA VEZ</small><strong>{previous ? previous.workout.date : 'Sin historial'}</strong><span>{lastWorking.length ? lastWorking.map((s) => `${s.weight || 0}×${s.reps || 0}`).join(' · ') : '—'}</span></div><div><small>RECOMENDACIÓN PARA HOY</small><strong>{recommendation ? actionLabels[recommendation.action] : 'Analizando…'} {recommendation?.recommendedWeight ? `· ${formatNumber(recommendation.recommendedWeight)} kg` : ''}</strong><span>{recommendation?.reason}</span></div></div>
    <div className="sets-head"><span>Serie</span><span>Tipo</span><span>Peso</span><span>Reps</span><span>Esfuerzo</span></div>{sets.map((set) => <SetRow key={set.id} set={set} increment={exercise.minIncrement} onComplete={completed} />)}
    <div className="set-actions"><Button variant="secondary" onClick={() => addSet()}><Plus /> Añadir serie</Button>{sets.length > 0 && <Button variant="ghost" onClick={() => addSet(sets.at(-1))}><Copy /> Copiar anterior</Button>}<span>{formatNumber(calculateExerciseVolume(sets), 0)} kg volumen</span></div>
  </Card>
}

function ExtraEntryModal({ workoutId, kind, onClose }: { workoutId: string; kind: 'cardio' | 'wod'; onClose: () => void }) {
  const [name, setName] = useState(kind === 'cardio' ? 'Correr' : ''); const [duration, setDuration] = useState(''); const [distance, setDistance] = useState(''); const [result, setResult] = useState('')
  async function submit(e: FormEvent) { e.preventDefault(); const now = nowIso(); if (kind === 'cardio') { const minutes = duration ? Number(duration) : null; const km = distance ? Number(distance) : null; await db.cardio.add({ id: uid(), workoutId, type: name, durationMinutes: minutes, distance: km, pace: minutes && km ? minutes / km : null, averageSpeed: minutes && km ? km / (minutes / 60) : null, calories: null, averageHeartRate: null, maxHeartRate: null, incline: null, resistance: null, effortZone: '', notes: result, createdAt: now, updatedAt: now } satisfies CardioEntry) } else { await db.wods.add({ id: uid(), workoutId, name, type: 'For time', durationMinutes: duration ? Number(duration) : null, timeCapMinutes: null, rounds: null, extraReps: null, finalTimeSeconds: null, rxWeight: null, usedWeight: null, scale: 'Escalado', movements: [], result, notes: '', createdAt: now, updatedAt: now } satisfies WodEntry) } toast.success(kind === 'cardio' ? 'Cardio añadido' : 'WOD añadido'); onClose() }
  return <Modal title={kind === 'cardio' ? 'Añadir cardio' : 'Añadir WOD'} onClose={onClose}><form onSubmit={submit} className="form-grid"><Input label={kind === 'cardio' ? 'Tipo de cardio' : 'Nombre del WOD'} required value={name} onChange={(e) => setName(e.target.value)} /><Input label="Duración (min)" type="number" min="0" value={duration} onChange={(e) => setDuration(e.target.value)} />{kind === 'cardio' && <Input label="Distancia (km)" type="number" min="0" step=".01" value={distance} onChange={(e) => setDistance(e.target.value)} />}<Input label={kind === 'cardio' ? 'Notas' : 'Resultado'} value={result} onChange={(e) => setResult(e.target.value)} /><div className="form-actions full"><Button variant="ghost" type="button" onClick={onClose}>Cancelar</Button><Button>Guardar</Button></div></form></Modal>
}

function FinishModal({ sets, onClose, onFinish }: { sets: SetEntry[]; onClose: () => void; onFinish: (feedback: Partial<Workout>) => Promise<void> }) {
  const [energy, setEnergy] = useState(''); const [effort, setEffort] = useState(''); const [performance, setPerformance] = useState(''); const [fatigue, setFatigue] = useState(''); const [pain, setPain] = useState(''); const [comments, setComments] = useState('')
  return <Modal title="Finalizar entrenamiento" onClose={onClose}><div className="finish-summary"><div><strong>{sets.length}</strong><span>series</span></div><div><strong>{effectiveSets(sets)}</strong><span>efectivas</span></div><div><strong>{totalReps(sets)}</strong><span>repeticiones</span></div><div><strong>{formatNumber(calculateWorkoutVolume(sets), 0)}</strong><span>kg de volumen</span></div></div><div className="form-grid"><Input label="Energía (1–5)" type="number" min="1" max="5" value={energy} onChange={(e) => setEnergy(e.target.value)} /><Input label="Esfuerzo general (1–10)" type="number" min="1" max="10" value={effort} onChange={(e) => setEffort(e.target.value)} /><Input label="Rendimiento (1–5)" type="number" min="1" max="5" value={performance} onChange={(e) => setPerformance(e.target.value)} /><Input label="Fatiga (1–5)" type="number" min="1" max="5" value={fatigue} onChange={(e) => setFatigue(e.target.value)} /><Input label="Molestias o dolor (texto libre)" value={pain} onChange={(e) => setPain(e.target.value)} /><Input label="Comentarios" value={comments} onChange={(e) => setComments(e.target.value)} /><div className="form-actions full"><Button variant="ghost" onClick={onClose}>Seguir entrenando</Button><Button onClick={() => onFinish({ energy: energy ? Number(energy) : null, effort: effort ? Number(effort) : null, performance: performance ? Number(performance) : null, fatigue: fatigue ? Number(fatigue) : null, pain, comments })}>Finalizar y guardar</Button></div></div><p className="medical-note">Las molestias se guardan como contexto. Pulso no diagnostica lesiones ni ofrece consejo médico.</p></Modal>
}

export function WorkoutPage() {
  const navigate = useNavigate(); const active = useLiveQuery(async () => (await db.workouts.where('status').equals('active').first()) ?? null, [])
  const links = useLiveQuery(() => active ? db.workoutExercises.where('workoutId').equals(active.id).sortBy('order') : [], [active?.id]) || []
  const sets = useLiveQuery(() => links.length ? db.sets.where('workoutExerciseId').anyOf(links.map((x) => x.id)).toArray() : [], [links.map((x) => x.id).join(',')]) || []
  const exercises = useLiveQuery(async () => (await db.exercises.orderBy('name').toArray()).filter((exercise) => exercise.active), []) || []
  const cardio = useLiveQuery(() => active ? db.cardio.where('workoutId').equals(active.id).toArray() : [], [active?.id]) || []; const wods = useLiveQuery(() => active ? db.wods.where('workoutId').equals(active.id).toArray() : [], [active?.id]) || []
  const [picker, setPicker] = useState(false); const [extra, setExtra] = useState<'cardio' | 'wod' | null>(null); const [finish, setFinish] = useState(false); const [record, setRecord] = useState(''); const [search, setSearch] = useState('')
  const settings = useLiveQuery(() => getSettings(), []); const currentExercises = links.map((l) => exercises.find((e) => e.id === l.exerciseId)).filter(Boolean) as Exercise[]; const rest = currentExercises.at(-1)?.restSeconds || settings?.defaultRestSeconds || 90
  if (active === undefined) return <div />
  if (!active) return <StartWorkout onStart={async (workout) => { await db.workouts.add(workout); toast.success('Sesión iniciada') }} />
  const activeWorkout = active
  async function addExercise(exercise: Exercise) { if (links.some((l) => l.exerciseId === exercise.id)) { toast.info('Ese ejercicio ya está en la sesión'); return } const now = nowIso(); const linkId = uid(); await db.transaction('rw', [db.workoutExercises, db.sets], async () => { await db.workoutExercises.add({ id: linkId, workoutId: activeWorkout.id, exerciseId: exercise.id, order: links.length, notes: '', createdAt: now, updatedAt: now }); await Promise.all(Array.from({ length: exercise.usualSets }, (_, index) => db.sets.add({ id: uid(), workoutExerciseId: linkId, order: index, type: 'Efectiva', weight: null, reps: exercise.targetMinReps, rir: null, rpe: null, completed: false, notes: '', completedAt: null, createdAt: now, updatedAt: now }))) }); setPicker(false) }
  async function complete(feedback: Partial<Workout>) { const end = localTime(); await db.transaction('rw', [db.workouts, db.personalRecords], async () => { for (const link of links) { const exerciseRecords = await db.personalRecords.where('exerciseId').equals(link.exerciseId).toArray(); const fresh = detectPersonalRecords(link.exerciseId, activeWorkout.id, sets.filter((s) => s.workoutExerciseId === link.id), exerciseRecords); if (fresh.length) await db.personalRecords.bulkAdd(fresh) } await db.workouts.update(activeWorkout.id, { ...feedback, status: 'completed', endTime: end, updatedAt: nowIso() }) }); toast.success('Entrenamiento completado'); navigate(`/historial/${activeWorkout.id}`) }
  return <div className="page active-workout"><div className="workout-top"><div><span className="live-pill"><i /> EN CURSO</span><h1>{activeWorkout.name || activeWorkout.type}</h1><p>{activeWorkout.date} · inicio {activeWorkout.startTime} · guardado automático</p></div><Button onClick={() => setFinish(true)}><Check /> Finalizar</Button></div><RestTimer initial={rest} />{record && <div className="pr-banner"><Trophy /> {record}<button onClick={() => setRecord('')}>✕</button></div>}
    {links.length ? links.map((link) => { const exercise = exercises.find((e) => e.id === link.exerciseId); return exercise ? <ExerciseBlock key={link.id} link={link} exercise={exercise} sets={sets.filter((s) => s.workoutExerciseId === link.id).sort((a,b) => a.order-b.order)} onRecord={setRecord} /> : null }) : <EmptyState icon={<Dumbbell />} title="Añade tu primer ejercicio" text="Solo se propondrán datos del ejercicio que tú elijas." />}
    {(cardio.length > 0 || wods.length > 0) && <Card className="extras-list"><h3>Bloques adicionales</h3>{cardio.map((x) => <div key={x.id}><Activity /><span><b>{x.type}</b><small>{x.durationMinutes || '—'} min · {x.distance || '—'} km</small></span><button onClick={() => db.cardio.delete(x.id)}><Trash2 /></button></div>)}{wods.map((x) => <div key={x.id}><Flame /><span><b>{x.name}</b><small>{x.type} · {x.result || 'sin resultado'}</small></span><button onClick={() => db.wods.delete(x.id)}><Trash2 /></button></div>)}</Card>}
    <div className="workout-add"><Button onClick={() => setPicker(true)}><Plus /> Añadir ejercicio</Button><Button variant="secondary" onClick={() => setExtra('cardio')}><Activity /> Cardio</Button><Button variant="secondary" onClick={() => setExtra('wod')}><Flame /> WOD</Button></div>
    {picker && <Modal title="Añadir ejercicio" onClose={() => setPicker(false)}><div className="search"><input autoFocus placeholder="Buscar ejercicio…" value={search} onChange={(e) => setSearch(e.target.value)} /></div><div className="picker-list">{exercises.filter((e) => e.name.toLowerCase().includes(search.toLowerCase())).map((e) => <button key={e.id} onClick={() => addExercise(e)}><span><strong>{e.name}</strong><small>{e.primaryMuscle} · {e.equipment}</small></span><Plus /></button>)}</div>{!exercises.length && <p>No hay ejercicios. Créalo primero desde la biblioteca.</p>}</Modal>}
    {extra && <ExtraEntryModal workoutId={activeWorkout.id} kind={extra} onClose={() => setExtra(null)} />}{finish && <FinishModal sets={sets} onClose={() => setFinish(false)} onFinish={complete} />}
  </div>
}
